### ISSUE TITLE
Create user interface with minimum features for the to-do app

### ISSUE THREAD

**Issue by bvenceslas** [bvenceslas/coding-test-todo#2]
- [x] Fetch data from JSON placeholder
- [x] while the app is still fetching from JSON placeholder, the user should see "Loading ..."
- [x] Create form to save new tasks
